name: Build and Deploy FITON Container App

on:
  push:
    branches:
      - main

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: fiton
  CONTAINER_APP_ENVIRONMENT_NAME: FITON
  RESOURCE_GROUP: CSP
  CONTAINER_REGISTRY_NAME: registryfiton
  CONTAINER_REGISTRY_LOGIN_SERVER: registryfiton.azurecr.io
  IMAGE_NAME: fiton-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}

      - name: Build Docker image
        run: |
          docker build --no-cache -f FITON.Server/Dockerfile -t ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name fiton \
            --resource-group CSP \
            --image registryfiton.azurecr.io/fiton-server:latest

